create tablespace dev
datafile 'C:\oracle_data\dev_ts.dbf' size 100M
AUTOEXTEND on next 10M MAXSIZE UNLIMITED;

alter session set "_ORACLE_SCRIPT"=TRUE;

create user development IDENTIFIED by "1234"
default TABLESPACE dev
TEMPORARY TABLESPACE temp 
quota UNLIMITED on dev;

create table development.currency_history
(
    history_id number GENERATED BY DEFAULT ON NULL as IDENTITY,
    balance_date date NOT NULL,
    base_currency varchar2(3) NOT NULL,
    target_currency varchar(3) NOT NULL,
    rate number(17,2),

    UNIQUE(balance_date, target_currency)
);

grant create session to development;
grant select, insert, update, delete on development.currency_history to development;
grant select_catalog_role to development;

BEGIN
    DBMS_NETWORK_ACL_ADMIN.ADD_PRIVILEGE(
        acl         => 'NETWORK_ACL_31824324071D46ECAE8EEF9B8980FDB2',
        principal   => 'DEVELOPMENT', 
        is_grant    => TRUE,
        privilege   => 'connect'
    );
    COMMIT;
END;

